Signup
Rodrigo-Miranda-0/target-frontend pull request #1
Opened 2024-01-26 18:21 UTC by Rodrigo-Miranda-0

This PR creates many of the components used through the landing page of the Target site.
It also creates logic elements such as:

- Router

- API request handler

Finally, it utilizes all previously mentioned items to create the `Signup` page

The `VITE_API_URL` environment variable is the current Heroku API server, and its value can be found [here](https://www.notion.so/rootstrap/Target-1c963bd0c09345668f4eb34ab4b5271a)

![Screenshot 2024-01-26 at 15 15 46](https://github.com/Rodrigo-Miranda-0/target-frontend/assets/56303269/0fc2da01-7a17-4d97-8712-d7479cbb2904)

2024-01-29 13:34 UTC, eugenialcaraz reviewed
Hey! Awesome job, Im adding some comments with suggestions and good practices. 
Let me know what do you think!

2024-01-29 13:34 UTC, eugenialcaraz commented on .prettierrc
> +{}
Will you have a setup here?

2024-01-29 13:34 UTC, eugenialcaraz commented on src/App.tsx
> +    </BrowserRouter>
Most probably you will add more routes in here, and the code can get a little repetitive. However you could create an array of routes and map through it. Something like this:

```suggestion

// before the return: 
//const routes = [
// {path:'/', element: <Navigate to='/signup'/>},
// {path:'/signup' element:<SignupPage/>}];

    <BrowserRouter>
      <Routes>
      {routes.map(({path,element}) => <Route path={path} element={element}/>)}
      </Routes>
    </BrowserRouter>
```

2024-01-29 13:34 UTC, eugenialcaraz commented on src/App.tsx
> +    </BrowserRouter>
Another suggestion is to use constants for all the strings you type manually across the whole app.
For example here you typed twice `'/signup'`, but if you have a file of constants and you import it from there,  typing mistakes wont break the app, and if in the future the client asks to change it to "create account" you just change it in one place

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/common/ButtonComponent.tsx
> +const ButtonComponent = (props: ButtonComponentProps) => {
You can destruct props in the component, so you don't have to use `props.className`, `props.onClick`, etc.

```suggestion
const ButtonComponent = ({ className, onClick, children, disabled }: ButtonComponentProps) => {
```

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/common/ButtonComponent.tsx
> +      } text-white text-center text-xs font-semibold bg-black self-center w-[185px] max-w-full justify-center items-center mt-6 px-16 py-4 max-md:px-5 disabled:opacity-30`}
You can add a default value of the className to be `""`, then you avoid the conditional. 
Another thing, the way you have it here, the `className` received will be overwritten by the fixed classes you added. If you want it to be the other way round, the received className needs to be at the end.

Like this the component classes will override the received `className`
```suggestion

//at the definition of the component: const ButtonComponent = ({ className = "", onClick, children, disabled }: //ButtonComponentProps) => {

      className={`${
        props.className
      } text-white text-center text-xs font-semibold bg-black self-center w-[185px] max-w-full justify-center items-center mt-6 px-16 py-4 max-md:px-5 disabled:opacity-30`}
```


Like this the received classes will override:

```suggestion
className={`text-white text-center text-xs font-semibold bg-black self-center w-[185px] max-w-full justify-center items-center mt-6 px-16 py-4 max-md:px-5 disabled:opacity-30 ${props.className} `}
```

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/common/LeftMainPanel.tsx
> +const LeftMainPanel = (props: { children: ReactElement }) => {
I think this works and `ts` doesn't scream:

```suggestion
const LeftMainPanel = ({ children}: ReactElement) => {
```

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/common/MainLayout.tsx
> +const MainLayout = (props: { children: ReactElement }) => {
Same here:
```suggestion
const MainLayout = ({ children}: ReactElement) => {
```

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/common/HamburgerMenu.tsx
> +      src="src/assets/menu.svg"
it's a good practice to import the src as an element
```suggestion

// top of the file: import { ReactComponent as Menu } from 'src/assets/menu.svg';
      src={Menu}
```

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/common/RightMainPanel.tsx
> +            srcSet="src/assets/i6.svg"
Same comment of the imports of the src here

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/login/LoginForm.tsx
> +export default LoginForm;
All the strings in the file manually typed can be converted to constants and reused

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/signup/SignupForm.tsx
> +  const [gender, setGender] = useState("");
```suggestion
  const [userData, setUserData] = useState({
  firstName:'',
  lastName:'',
  userName:'',
  email:'',
  password:'',
  confirmPassword:'',
  gender:''});
```

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/signup/SignupForm.tsx
> +  };
```suggestion
  const handleUserData = (e: FormEvent<HTMLInputElement>, field) => {
    setUserData({...userData, [field]:e.currentTarget.value});
  };
```

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/signup/SignupForm.tsx
> +      confirmPassword != password
```suggestion
     Object.values(userData).some('') ||
      confirmPassword != password
```

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/signup/SignupForm.tsx
> +        </div>
Maybe creating a common input component will be a good idea here, as you are repeating most of the code

2024-01-29 13:34 UTC, eugenialcaraz commented on src/components/signup/SignupForm.tsx
> +        <p className="self-center text-xs, mt-3 font-semibold">SIGN IN</p>
I think this should be an `<a>` in the future

2024-01-29 14:01 UTC, Ivan-Encinas requested changes
Great job, just check out the suggestions in the comments

2024-01-29 14:01 UTC, Ivan-Encinas commented on src/components/login/LoginForm.tsx
> +  };
You can avoid all this if you use React hook form, maybe its a good opportunity to try it.

2024-01-30 15:31 UTC, Rodrigo-Miranda-0 commented on src/components/common/MainLayout.tsx
> +const MainLayout = (props: { children: ReactElement }) => {
I actually get the `Property 'children' does not exist on type 'ReactElement<any, string | JSXElementConstructor<any>>'` error once i do this

2024-01-30 15:44 UTC, Ivan-Encinas commented on src/components/common/MainLayout.tsx
> +const MainLayout = (props: { children: ReactElement }) => {
`const MainLayout = ( children : ReactElement) => ` is without the brackets

2024-01-30 15:47 UTC, Ivan-Encinas commented on src/components/common/LeftMainPanel.tsx
> +const LeftMainPanel = (props: { children: ReactElement }) => {
Same here with the brackets in children

2024-02-02 16:43 UTC, merged